name: build_deploy_aks
on:
  push:
    paths:
      - "Application/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: check values
        run: |
          echo ${{ secrets.registry }}
          echo ${{ secrets.repository }}
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image:  cosmosaks
          git_access_token: ${{ secrets.GITHUB_TOKEN }} # Use secrets.GITHUB_TOKEN for public repo or create a PAT secrets.GIT_ACCESS_TOKEN for private repo
          folder: Application
          branch: main
          tag: ${{ github.sha }}
      - name: Azure login
        id: login
        uses: azure/login@v1.4.7
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}' 
          cluster-name: '${{ secrets.cluster_name }}'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'todoapp'
          manifests: |
             Bicep/akstododeploy.yml
          images: '${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}:${{ github.sha }}'
          pull-images: false
